spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off

  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace #바인딩된 파라미터까지 볼 수 있도록
