spring:
  datasource:
    url: jdbc:mariadb://dev1.inphr.com:3306/self_isolation?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        # ?page=1 -> offset 0으로 계산하는 설정
        one-indexed-parameters: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace #바인딩된 파라미터까지 볼 수 있도록


# Spring Actuator
management:
  endpoints:
    web:
      # 기본 path로서 잘 알려진 /actuator를 노출하지 않도록 변경
      base-path: /monitor
      exposure:
        # health와 metric만 public으로 노출
        include: health,metrics
