spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        # ?page=1 -> offset 0으로 계산하는 설정
        one-indexed-parameters: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace #바인딩된 파라미터까지 볼 수 있도록
